source "https://rubygems.org"

gem "railties", "8.1.4"
gem "actionpack", "8.1.4"
gem "actionview", "8.1.4"
gem "activerecord", "8.1.4"
gem "pg", "1.6.3"
gem "puma", "8.0.2"
gem "net-smtp", "0.5.1"
gem "csv", "3.3.6"

# Versions tools/vendor.rb holds back as too recent; regenerated by `update`.
# cooldown: begin
gem "rdoc", "!= 8.1.0", require: false
# cooldown: end
