#!/usr/bin/env ruby
# frozen_string_literal: true

# The dependency toolchain: resolve, vendor, verify, and describe the gems.
#
#   tools/vendor.rb update     re-resolve under the cooldown, refill vendor/cache,
#                              and rewrite dependencies.json (network)
#   tools/vendor.rb sync       download any locked gem missing from vendor/cache (network)
#   tools/vendor.rb manifest   rewrite dependencies.json only (network)
#   tools/vendor.rb check      verify Gemfile, Gemfile.lock, vendor/cache, and
#                              dependencies.json against each other (offline)
#
# Every gem is locked for the "ruby" platform only, so each is built from its
# published source on install rather than taken as a precompiled binary.
# vendor/cache holds the .gem files, committed; `bundle install --local`
# installs from there and never contacts rubygems.org. Standard library only,
# and run with the system Ruby outside the bundle.

require "digest"
require "json"
require "net/http"
require "rubygems/package"
require "time"
require "uri"

ROOT = File.expand_path("..", __dir__)
GEMFILE = File.join(ROOT, "Gemfile")
LOCK = File.join(ROOT, "Gemfile.lock")
CACHE = File.join(ROOT, "vendor", "cache")
MANIFEST = File.join(ROOT, "dependencies.json")
COOLDOWN_DAYS = 7
COOLDOWN_BEGIN = "# cooldown: begin"
COOLDOWN_END = "# cooldown: end"

def die(message)
  warn "vendor.rb: #{message}"
  exit 1
end

def get_json(path)
  uri = URI("https://rubygems.org#{path}")
  4.times do |attempt|
    res = Net::HTTP.get_response(uri)
    return JSON.parse(res.body) if res.is_a?(Net::HTTPSuccess)
    die "GET #{uri}: #{res.code}" unless res.code == "429" && attempt < 3
    sleep 2**attempt
  end
end

def bundle(*args)
  env = { "BUNDLE_FROZEN" => "false", "BUNDLE_FORCE_RUBY_PLATFORM" => "true" }
  system(env, "bundle", *args, chdir: ROOT, exception: true)
end

# The root pins, {name => version}, outside the cooldown block.
def root_pins
  pins = {}
  text = File.read(GEMFILE)
  text = text.sub(/#{COOLDOWN_BEGIN}.*#{COOLDOWN_END}/m, "")
  text.scan(/^\s*gem\s+"([^"]+)"(.*)$/) do |name, rest|
    version = rest[/\A,\s*"(?:= ?)?(\d[^"]*)"/, 1]
    die "Gemfile: #{name} must be pinned to an exact version" if version.nil? || version !~ /\A[\d.]+\z/
    pins[name] = version
  end
  pins
end

# The locked gems, [[name, version]], and their CHECKSUMS entries.
def locked
  lock = File.read(LOCK)
  specs = lock[/^GEM\n.*?^  specs:\n(.*?)^\n/m, 1] or die "Gemfile.lock has no GEM specs"
  gems = specs.scan(/^    (\S+) \(([^)]+)\)$/)
  platforms = lock[/^PLATFORMS\n(.*?)^\n/m, 1].split.uniq
  die "Gemfile.lock must lock the ruby platform only, not #{platforms.join(', ')}" unless platforms == ["ruby"]
  gems.each { |n, v| die "#{n} #{v} is a platform-specific gem" if v.include?("-") }
  sums = lock.scan(/^  (\S+) \(([^)]+)\) sha256=(\h{64})$/).to_h { |n, v, s| ["#{n}-#{v}", s] }
  [gems, sums]
end

def write_cooldown(excluded)
  lines = excluded.sort.map { |n, v| %(gem "#{n}", "!= #{v}", require: false) }
  block = [COOLDOWN_BEGIN, *lines, COOLDOWN_END].join("\n")
  text = File.read(GEMFILE)
  text = if text.include?(COOLDOWN_BEGIN)
    text.sub(/#{COOLDOWN_BEGIN}.*#{COOLDOWN_END}/m, block)
  else
    "#{text.chomp}\n\n# Versions tools/vendor.rb holds back as too recent; regenerated by `update`.\n#{block}\n"
  end
  File.write(GEMFILE, text)
end

def published(name, version)
  @versions ||= {}
  @versions[name] ||= get_json("/api/v1/versions/#{name}.json")
  v = @versions[name].find { |x| x["number"] == version && x["platform"] == "ruby" }
  die "#{name} #{version} is not on rubygems.org" unless v
  Time.parse(v["created_at"])
end

def update
  pins = root_pins
  excluded = []
  cutoff = Time.now - COOLDOWN_DAYS * 86_400
  loop do
    write_cooldown(excluded)
    bundle("lock", "--update", "--add-checksums")
    gems, = locked
    recent = gems.select { |n, v| published(n, v) > cutoff }
    break if recent.empty?

    recent.each do |n, v|
      die "#{n} #{v} is pinned in the Gemfile but was published less than #{COOLDOWN_DAYS} days ago" if pins[n] == v
      puts "holding back #{n} #{v} (published #{published(n, v).to_date})"
    end
    excluded |= recent
  end
  sync
  manifest
  check
end

# Make vendor/cache hold exactly the locked .gem files, downloading any that
# are missing and checking each against its locked sha256.
def sync
  gems, sums = locked
  wanted = gems.map { |n, v| "#{n}-#{v}.gem" }
  Dir.mkdir(CACHE) unless Dir.exist?(CACHE)
  gems.each do |n, v|
    path = File.join(CACHE, "#{n}-#{v}.gem")
    next if File.exist?(path) && Digest::SHA256.file(path).hexdigest == sums["#{n}-#{v}"]

    data = fetch("https://rubygems.org/gems/#{n}-#{v}.gem")
    die "#{n} #{v}: download does not match its locked checksum" unless Digest::SHA256.hexdigest(data) == sums["#{n}-#{v}"]
    File.binwrite(path, data)
    puts "vendored #{n} #{v}"
  end
  (Dir.children(CACHE).select { _1.end_with?(".gem") } - wanted).each do |f|
    File.delete(File.join(CACHE, f))
    puts "removed #{f}"
  end
end

def fetch(url, redirects = 5)
  res = Net::HTTP.get_response(URI(url))
  return res.body if res.is_a?(Net::HTTPSuccess)
  return fetch(res["location"], redirects - 1) if res.is_a?(Net::HTTPRedirection) && redirects.positive?

  die "GET #{url}: #{res.code}"
end

# Every gem is runtime: the server needs the framework's whole tree, tests run
# on minitest and rack-test, which the framework itself requires, and there is
# no build step.
def manifest
  gems, = locked
  owners = gems.to_h do |n, _|
    [n, get_json("/api/v1/gems/#{n}/owners.json").map { |o| "rubygems:#{o.fetch('handle')}" }.sort]
  end
  bytes = lines = 0
  gems.each do |n, v|
    b, l = unpacked_size(File.join(CACHE, "#{n}-#{v}.gem"))
    bytes += b
    lines += l
  end
  doc = {
    "format" => "tadmor-dependencies/1",
    "generator" => "tools/vendor.rb manifest (tadmor-ruby)",
    "platform" => "linux/x64",
    "toolchains" => ["Ruby (the operating system's build), with RubyGems and Bundler",
                     "the operating system's C compiler and libpq, for native extensions"],
    "packages" => gems.map do |n, v|
      { "ecosystem" => "rubygems", "name" => n, "version" => v, "category" => "runtime",
        "identities" => owners[n], "evidence" => "https://rubygems.org/api/v1/gems/#{n}/owners.json" }
    end,
    "sources" => [{ "label" => "RubyGems vendor/cache (runtime, unpacked)", "bytes" => bytes, "lines" => lines }],
  }
  File.write(MANIFEST, "#{JSON.pretty_generate(doc)}\n")
  puts "wrote dependencies.json: #{gems.size} gems, #{owners.values.flatten.uniq.size} owner accounts"
end

# Unpacked bytes, and non-blank lines of the text files, in a .gem.
def unpacked_size(path)
  bytes = lines = 0
  Gem::Package.new(path).spec # verifies the archive's own checksums
  File.open(path, "rb") do |io|
    Gem::Package::TarReader.new(io).each do |entry|
      next unless entry.full_name == "data.tar.gz"

      Zlib::GzipReader.wrap(StringIO.new(entry.read)) do |gz|
        Gem::Package::TarReader.new(gz).each do |file|
          next unless file.file?

          data = file.read || ""
          bytes += data.bytesize
          lines += data.each_line.count { |l| !l.strip.empty? } unless data.include?("\0")
        end
      end
    end
  end
  [bytes, lines]
end

def check
  pins = root_pins
  gems, sums = locked
  versions = gems.to_h
  pins.each do |n, v|
    die "Gemfile pins #{n} #{v} but Gemfile.lock has #{versions[n] || 'none'}" unless versions[n] == v
  end
  wanted = gems.map { |n, v| "#{n}-#{v}.gem" }.sort
  present = Dir.children(CACHE).select { |f| f.end_with?(".gem") }.sort
  die "vendor/cache lacks #{(wanted - present).join(', ')}" unless (wanted - present).empty?
  die "vendor/cache has unlocked #{(present - wanted).join(', ')}" unless (present - wanted).empty?
  gems.each do |n, v|
    sum = sums["#{n}-#{v}"] or die "Gemfile.lock has no checksum for #{n} #{v}"
    actual = Digest::SHA256.file(File.join(CACHE, "#{n}-#{v}.gem")).hexdigest
    die "vendor/cache/#{n}-#{v}.gem does not match its locked checksum" unless actual == sum
  end
  listed = JSON.parse(File.read(MANIFEST))["packages"].map { |p| [p["name"], p["version"]] }.sort
  die "dependencies.json does not list exactly the locked gems" unless listed == gems.sort
  puts "ok: #{gems.size} gems locked, vendored, and listed"
end

case ARGV
in ["update"] then update
in ["sync"] then sync
in ["manifest"] then manifest
in ["check"] then check
else
  warn "usage: tools/vendor.rb update|sync|manifest|check"
  exit 2
end
